trigger:
- main
- feature

pool: 'mypool'

stages:

# ------------------ PLANNING ------------------
- stage: Planning_Stage
  jobs:

  - job: Terraform_Init
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra_code'
        backendServiceArm: 'myfirstproject'
        backendAzureRmResourceGroupName: 'myrg'
        backendAzureRmStorageAccountName: 'storageaccount'
        backendAzureRmContainerName: 'tfstate'
        backendAzureRmKey: 'alt.tfstate'

  - job: Terraform_Fmt
    dependsOn: Terraform_Init
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'custom'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra_code'
        outputTo: 'console'
        customCommand: 'fmt'
        environmentServiceNameAzureRM: 'myfirstproject'

  - job: Terraform_Validate
    dependsOn: Terraform_Fmt
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'validate'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra_code'

  - job: Terraform_Plan
    dependsOn: Terraform_Validate
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra_code'
        environmentServiceNameAzureRM: 'myfirstproject'


# ------------------ SECURITY ------------------
- stage: Security_Checks
  dependsOn: Planning_Stage
  jobs:
  - job: tfsec_scan
    steps:
    - task: tfsec@1
      inputs:
        version: 'v1.26.0'
        dir: '$(System.DefaultWorkingDirectory)/infra_code'


# ------------------ APPROVAL ------------------
- stage: Approval_Stage
  dependsOn: Security_Checks
  jobs:
  - job: Manual_Approval
    pool: server
    steps:
    - task: ManualValidation@1
      inputs:
        notifyUsers: 'kashafrocks@gmail.com'
        instructions: 'Approve before apply'


# ------------------ APPLY ------------------
- stage: Apply_Stage
  dependsOn: Approval_Stage
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  jobs:
  - job: Terraform_Apply
    steps:
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)/infra_code'
        environmentServiceNameAzureRM: 'myfirstproject'